{% set name = "prawn" %}
{% set version = "2.4.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 82062744f7126c2d77501da253a154271790254dfa8c309b8e52e79bc5de2abd

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - pdf-core ~> 0.9.0
    - ttfunk ~> 1.7

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/prawn
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Prawn renders SVG directly into PDF documents.
  doc_url: http://www.rubydoc.info/gems/prawn
  dev_url: https://github.com/prawnpdf/prawn

extra:
  recipe-maintainers:
    - rudispr
